set(debugcmake false)
if(debugcmake)
get_cmake_property(_variableNames VARIABLES)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
endif()

MESSAGE(STATUS "-------------------- Summary --------------------")
MESSAGE(STATUS "cmake build type : '${CMAKE_BUILD_TYPE}'")
MESSAGE(STATUS "mpi : '${MPICOMPILE}'")
MESSAGE(STATUS "CXX Compiler ID  : ${CMAKE_CXX_COMPILER_ID}")
MESSAGE(STATUS "CXX Compiler  : ${CMAKE_CXX_COMPILER}")
MESSAGE(STATUS "CXX Compiler flags : ${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}}")
get_directory_property( directories DIRECTORY ${CMAKE_SOURCE_DIR} COMPILE_DEFINITIONS )
MESSAGE(STATUS "CXX own FLags :  ${directories}")
get_property(directories DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY INCLUDE_DIRECTORIES)
MESSAGE(STATUS "CXX Include directories :  ${directories}")
MESSAGE(STATUS "Installation directory : ${CMAKE_INSTALL_PREFIX}")
MESSAGE(STATUS "Cmake module path : ${CMAKE_MODULE_PATH}")
MESSAGE(STATUS "Source directory : ${CMAKE_SOURCE_DIR}")
MESSAGE(STATUS "SIMFEM_EXTERNAL_LINKLIBS : ${SIMFEM_EXTERNAL_LINKLIBS}")
MESSAGE(STATUS "SIMFEM_EXTERNAL_INCLUDES : ${SIMFEM_EXTERNAL_INCLUDES}")
MESSAGE(STATUS "SIMFEM_INCLUDES : ${SIMFEM_INCLUDES}")
MESSAGE(STATUS "PYTHON_LIBRARIES : ${PYTHON_LIBRARIES}")
MESSAGE(STATUS "Boost_LIBRARIES : ${Boost_LIBRARIES}")
MESSAGE(STATUS "-------------------------------------------------")
